import type { Copy } from "./copy";

export const copyEn: Copy = {
  appName: "KStar",
  appNameFull: "KStar Discovery",
  tagline: "Like this idol? You'll love these too",
  searchPlaceholder: "Search idols…",
  search: "Search",
  popularArtists: "Popular idols",
  featuredArtists: "Featured idols",
  similarArtistsTitle: "If you like this idol, you might also like…",
  discoverSimilar: "Discover similar idols →",
  genres: "Genres",
  noResults: "No results",
  noResultsHint: "Try the idol's English name or group, or browse the directory.",
  searchBrowseDirectory: "Browse the idol directory →",
  searchResultsFor: (q: string) => `Results for “${q}”`,
  artistsSection: "Idols",
  favorite: "Favorite",
  favorited: "Favorited",
  myFavorites: "My favorites",
  noFavorites: "You haven't favorited any idols yet.",
  backHome: "Back home",
  loginCta: "Sign in to sync favorites across devices",
  viewArtist: "View idol",
  startBtn: "Start over",
  taskbarLabel: "♪ K-pop picks",
  navDirectory: "Idol directory",
  footerCredit: "Recommendations from genres & metadata · Data from Spotify",
  footerSubmit: "✦ Submit idol photos",
  bugReportLabel: "Report a problem",
  bugReportSubject: "KStar problem report",
  bugReportBody: "Describe the problem (with screenshots and steps to reproduce):\n\n",

  // ── idol directory ────────────────────────────────────────────────
  dirCountSuffix: " idols",
  viewList: "List",
  viewStar: "Star map",
  filterGender: "Type",
  filterGen: "Gen",
  filterPos: "Role",
  noMatches: "No idols match. Try loosening the filters",
  showingPrefix: "Showing ",
  perPageLabel: "Per page",
  prevPage: "‹ Prev",
  nextPage: "Next ›",
  addToFourCutsAria: (name: string) => `Swap ${name} into your four cuts`,
  addToFourCutsTitle: "Swap into your four cuts",

  // ── four cuts / onboarding picker ─────────────────────────────────
  obTitlePick: "Pick your TOP 4",
  fourCutsTitle: "Your Four Cuts",
  obTitleQuiz: "Fan Soul Quiz",
  obPickPrompt: "Who are your four favorite idols?",
  obPickCount: (n: number, max: number) => `Pick your Top 4 · ${n}/${max} selected`,
  obSkip: "Skip for now",
  obDevelop: "Develop the photos →",
  obFourCutsSub: "A booth shot with your biases",
  obAnalyzing: "Analyzing your taste…",
  obRepick: "← Re-pick",
  noTop4: "You haven't picked your TOP 4 yet",
  pickTop4Btn: "Pick your TOP 4 →",
  repickBtn: "Re-pick ✎",
  swapTitle: "Swap a cut",
  swapIncoming: "Coming in",
  swapPrompt: "Tap a cut to swap it out ↓",
  swapThisCut: "Swap this cut",
  cancel: "Cancel",
  addPhoto: "Add photo",
  addPhotoAria: (name: string) => `Add a photo for ${name}`,

  // ── fan soul / onboarding quiz ─────────────────────────────────────
  soulCtaTitle: "Curious about your fan soul?",
  soulCtaSub: "Answer a few questions to unlock your fan personality card ✦",
  soulCtaStart: "Start the quiz →",
  soulCtaSkip: "Just browsing",
  rankTitle: "What pulls you in first?",
  rankSub: "Use ▲▼ to order them — top is what you care about most",
  rankHint: "#1 matters most → #4 least",
  quizProgress: (i: number, n: number) => `Question ${i} / ${n}`,
  quizBack: "← Previous",
  resultTitle: "Your fan soul",
  resultHidden: "Hidden side",
  resultSoulmate: "Souls like yours",
  resultExpand: "Want to widen your world? Try",
  resultWallClimb: "You're most likely to bias-swap to",
  resultRecap: "Your defining picks",
  shareDownload: "Download fan card",
  shareShare: "Share ✦",
  shareHint: "Screenshot it to your story so friends can test too",
  // invite link — sends newcomers to the first-encounter onboarding at "/"
  inviteBtn: "✦ Copy invite link",
  inviteCopied: "Copied. Send it to a friend ✓",
  inviteText: "Find your fan soul on KStar and meet your bias ✦",
  reshareEntry: "My fan soul",
  takeQuiz: "Find my fan soul",
  soulEvolving: "Your fan soul is evolving",
  processing: "Processing…",
  exportFailedReport: "Image export failed. Long-press or screenshot this report to share instead ✦",
  exportFailedStory: "Image export failed. Long-press or screenshot this card to share instead ✦",
  exportFailedPass: "Image export failed. Long-press or screenshot to share instead ✦",
  doneBtn: "✦ Done",
  contrastYesLine: "Duality: the most charming part is being different on and off stage",
  contrastNoLine: "Consistency: the same person from every angle",
  soulmateNote: "You two would bias-swap together",
  expandNote: "Fills in the side you haven't explored yet",
  wallClimbNote: "Your next bias might be here",
  wallClimbGroupSuffix: (name: string) => `the “${name}” crowd`,
  shareTextReport: (name: string, code: string) => `I'm a "${name}" (${code}) ✦ Find yours →`,
  compatSuffix: (pct: number) => `${pct}% match`,
  constelLoading: "Arranging your star map…",
  constelNeedPicks: "Pick your Top 4 first to see your star map ✦",
  constelStart: "Start picking →",
  constelTitle: "✦ Your Fan Star Map",
  nextStep: "Next →",
  moveUp: "Move up",
  moveDown: "Move down",
  defaultPickName: "them",
  defaultOutlierName: "one of them",
  soulLabel: "Fan Soul",
  passShareText: (topLabel: string) => `${topLabel} fan pass ✦`,
  loadingLabel: "Loading…",

  // ── artist page analysis sections ───────────────────────────────────
  analysisIdol: "Idol Analysis",
  analysisAesthetic: "Aesthetic Analysis",
  analysisPersonality: "Personality Analysis",
  analysisPerformance: "Performance Analysis",
  analysisContent: "Content Analysis",
  colorLabel: "Color Palette",
  officialStyle: "Official Styling",
  personalStyle: "Personal Style",
  instagramLabel: (handle: string) => `Instagram @${handle}`,
  similarTraitsPrefix: (traits: string) => `Similar traits: ${traits}`,

  // ── intro splash flash-warning gate ─────────────────────────────────
  introGateTitle: "⚠ Flash Warning",
  introGateHeading: "The opening animation contains flashing effects",
  introGateBody: "This opening animation contains flashing lights that may affect those with photosensitivity. Play it?",
  introPlayBtn: "Play animation",
  introCalmBtn: "Calm version",

  // ── /submit portal ───────────────────────────────────────────────────
  submitPageTitle: "Submit Idol Photos · KSTAR",
  submitNotConfiguredTitle: "✦ Submissions Not Enabled ✦",
  submitNotConfiguredBody: "This site hasn't configured a submission backend yet.",
  submitBadge: "✦ Help Fill In Idol Photos ✦",
  submitTitle: "These idols still need photos",
  submitSub: "Tap one to start · Free-license only (CC / your own)",
  submitSearchPlaceholder: "🔍 Find another idol (can also submit a replacement)…",
  submitMissingTag: "No photo",
  submitChangeIdol: "← Change idol",
  submitSelected: "✓ Selected",
  submitPhotoLabel: "Photo",
  submitSourceLabel: "Source link (required)",
  submitLicenseLabel: "License",
  submitCreditLabel: "Credit (optional)",
  submitCreditPlaceholder: "Your name/IG, shown as credit",
  submitBtnBusy: "Submitting…",
  submitBtnIdle: "Submit → awaiting review",
  submitSuccessBadge: "✦ Submitted ✦",
  submitSuccessMsg: (name: string) => `${name}'s photo has been submitted and will go live after review. Thank you!`,
  submitAgain: "← Submit another",
  submitErrorDefault: "Submission failed",
  licenseOwn: "Taken by me",
  favoritesStorageNote: "Favorites are saved only in this browser.",
  // result views (toggle + report)
  viewFourCut: "Four cuts",
  viewStory: "Story card",
  viewReport: "Full report",
  storyCta: "Find your fan soul →",
  reportLayers: "The four layers",
  reportAnswers: "Your answers",
  reportUniverse: "Your fan universe",
  reportContrast: "Contrast vs. consistency",
  reportVisual: "The visual type that gets you",
  reportResonance: "What resonates with you most",
  shareDownloadStory: "Download story card",
  shareDownloadReport: "Download full report",
  redoQuiz: "Retake the quiz",
  retakeQuiz: "↻ Retake",
  pickColor: "Colour",
  pickColorTitle: "Pick a colour",
  // 16 fan-soul types explanation page
  soulTypesTitle: "The 16 Fan-Soul Types",
  soulTypesIntro: "Each type is built from whether 4 layers score \"high\": Aesthetic (A) / Personality (P) / Stage (S) / Resonance (R). Your type is derived from the 4 idols you pick; it isn't a separate quiz.",
  soulTypesCta: "Back home to find yours →",
  soulTypesYours: "This is your type",
  soulTypesSeeOthers: "See the other 15 types →",
  soulTypesMissingLabel: "One blind spot",
  tierOmnivore: "Zero highs · The omnivore",
  tierPurist: "One high · The purists",
  tierDuality: "Two highs · The dualities",
  tierNearPerfect: "Three highs · The near-perfect",
  tierLegend: "Four highs · The legend",
  footerSoulTypes: "✦ The 16 fan-soul types",
  // Fan ID (deployed rebrand of the former fan pass)
  viewPass: "Fan ID",
  passPickIdol: "Who is this Fan ID for?",
  passUploadTitle: "Add your photo",
  passUploadHint: "Stays on your device, never uploaded ✦",
  passUploadBtn: "Choose photo",
  passCropTitle: "Adjust your ID photo",
  passCropHint: "Drag to move, slide to zoom",
  passCropConfirm: "Done. Make my Fan ID ✦",
  passRetake: "Pick another photo",
  passChangeIdol: "← Change idol",
  passNameLabel: "Your name",
  passNamePlaceholder: "Enter a nickname…",
  passMember: "MEMBER",
  passSince: (y: number) => `since ${y}`,
  passFooter: "✦ CHEERING ✦",
  passSeal: "CHEERING",
  passSolo: "✦ SOLO ✦",
  passDownload: "Download Fan ID",

  // ── deployed brand hero + Fan ID wizard ──
  taglineEn: "KSTAR SOULCUTS",
  wizStartCta: "Start building your fan profile",
  wizLandingNote: "Claim your Fan ID in three minutes",
  wizEscape: "Browse the idol directory first →",
  wizStep1: "Build your bias lineup",
  wizStep2: "Fan-style quiz",
  wizStep3: "Your result",
  wizStep4: "Claim your Fan ID",
  wizNodeRank: "Rank layers",
  wizNodeQuiz: "Soul quiz",
  wizNext: "Next",
  wizBack: "Back",
  wizDevelop: "Develop the photos →",
  wizIssueCta: "Claim my Fan ID →",
  wizPrinting: "Printing your card…",
  wizDone: "Enter my fan base →",
  wizPickHint: (n: number) => `${n}/4 biases picked`,
  fanIdName: "Fan ID",
  fanIdHolder: "Cardholder",
  fanIdHolderPlaceholder: "Unnamed fan",
  editFanId: "Edit Fan ID ✎",
  decorateFourCut: "Decorate ✎",
  fourCutDone: "Done",
  fourCutFrameLabel: "Frame",
  fourCutCaptionLabel: "Caption",
  fourCutCaptionPlaceholder: "e.g. Summer 2026 · my bias",
  fourCutDownload: "Download",
  fourCutShare: "Share",
  fanIdOpenFailed: "Couldn't open, please try again",
  addToFourCut: "+ Add to Four Cuts",
  inFourCut: "✓ In your Four Cuts",
  fourCutSwapToast: (added: string, removed: string) => `Added ${added}, removed ${removed}`,
  fourCutAddToast: (added: string) => `Added ${added} to your Four Cuts`,
  undoAction: "Undo",
  fanIdSong: "Bias song",
  fanIdScanMe: "Scan to make your Fan ID",
  fanIdClaim: "Claim your Fan ID",
  myFanId: "My Fan ID",
  fanIdBrandHeading: "KSTAR Fan ID Center",
  fanIdBrandSub: "Build your fan profile first",
  storyFrequency: "Your fan frequency",

  // ── /start wizard ──────────────────────────────────────────────────
  wizCenterSuffix: "Fan ID Center",
  startPageTitleSuffix: "Claim your Fan ID",
  wizDeveloping: "Developing…",
  wizDevelopFailed: "Failed to develop. Please go back and try again.",
  wizResultLoadFailed: "Couldn't load your result. Please go back and try again.",
  wizNeedFourPicks: "Your Fan ID needs four picks. Please go back and choose again.",
  wizNeedArchetype: "You haven't finished the quiz yet. Please go back and take it.",
  wizCardLoadFailed: "Couldn't load your card data. Please go back and try again.",
  wizPreparingCard: "Preparing your card…",
  wizUnderConstruction: "Under construction",
  wizStepsAria: "Steps",
  wizQuizComplete: "Quiz complete ✦",
  wizViewResult: "See your result →",
  wizRedoQuiz: "↻ Retake the quiz",
  wizPickThumbsAria: "Bias thumbnails",
  wizQuizProgressAria: "Quiz progress",
  wizDefaultPickName: "them",

  // ── /start wizard: step picker ────────────────────────────────────
  wizPickSlotLabel: "Bias slots",
  wizSwapHint: (name: string) => `${name} · tap two slots to swap`,
  wizRemoveAria: (name: string) => `Remove ${name}`,
  wizEmptySlotAria: (n: number) => `Empty bias slot ${n}`,
  wizPickToggleAria: (picked: boolean, name: string) => `${picked ? "Remove" : "Pick"} ${name}`,
  pagePrevAria: "Previous page",
  pageNextAria: "Next page",
  filterAllGen: "All generations",

  // ── /start wizard: reveal ──────────────────────────────────────────
  shareTabsAria: "Choose what to share",
  shareTabReport: "Full image",
  shareStudioAria: "Share your fan result",

  // ── /start wizard: issue (fan ID ceremony) ─────────────────────────
  wizIncompleteAlert: "Your Fan ID data is incomplete. Please go back and pick four again.",
  wizFocusLabel: "Choose your hero focus",
  wizFanNameLabel: "Cardholder (optional)",
  wizCardVersionLabel: "Card version",
  wizVersionA: "Version A · With photo",
  wizVersionB: "Version B · Share only",
  wizBiasSongComingSoon: "Bias song ♪ · card deco (coming soon)",
  wizExporting: "Exporting…",
  wizExportStory: "Export story 9:16",
  wizExportCard: "Export card",
  wizExportFailedGeneric: "Export failed. Please try again later or take a screenshot.",
  wizReplay: "↻ Replay the ceremony",
  wizSaveFailed: "Couldn't save your Fan ID. Check your browser storage and try again.",
  customizeFanIdAria: "Customize your Fan ID",
  stickerTrayTitle: "Custom stickers",
  stickerTraySubtitle: "Place them anywhere; overlapping is part of the fun.",
  stickerPacksAria: "Sticker packs",
  stickerClearPlaced: "Clear placed stickers",
  stickerAdd: (label: string) => `Add ${label}`,
  stickerMove: (label: string) => `Move ${label}`,
  stickerResize: (label: string) => `Resize ${label}`,
  stickerRotate: (label: string) => `Rotate ${label}`,
  stickerRemove: (label: string) => `Remove ${label}`,
  cardEditionLabel: "Card edition",

  // ── face photo picker ───────────────────────────────────────────────
  closeAria: "Close",
  photoZoomAria: "Photo zoom",
  cropBusy: "Cropping…",
  cropConfirmBtn: "Use this photo",
  fanIdPhotosTitle: "Photos",
  fanIdPhotosSummaryOriginal: "Using original photos",
  fanIdPhotosSummaryCustom: "Custom local photos",
  fanIdPhotoOriginal: "Original",
  fanIdPhotoCustomLocal: "Custom · on this device",
  fanIdPhotoReplace: "Replace",
  fanIdPhotoAdjust: "Adjust",
  fanIdPhotoUseOriginal: "Use original",
  fanIdUserPhoto: "Your photo",
  fanIdUserPortrait: "Portrait",
  fanIdUserAvatar: "Avatar",
  fanIdPhotoStoredLocal: "Stored only in this browser. Nothing is uploaded.",
  fanIdPhotoPermissionNote: "Choose a photo you have permission to use.",
  fanIdPhotoRemove: "Remove",
  fanIdPhotoRemoveAll: "Remove all local photos",
  fanIdPhotoRemoveAllConfirm: "Remove all local photos from this browser?",
  fanIdPhotoUnsupportedType: "Choose a JPG, PNG, or WebP photo.",
  fanIdPhotoTooLarge: "Choose a photo smaller than 15 MB.",
  fanIdPhotoDecodedTooLarge: "This photo is too large to process.",
  fanIdPhotoDecodeFailed: "Couldn't read this photo. Please choose another one.",
  fanIdPhotoStorageUnavailable: "Local photo storage is unavailable in this browser.",
  fanIdPhotoStorageFull: "This browser's local photo storage is full.",
  fanIdPhotoUseFraming: "Use this framing",
  fanIdPhotoResetFraming: "Reset framing",
  photoProcessFailed: "Couldn't process the photo. Please try a different one.",
  facePhotoChange: "Change your photo",
  facePhotoAdd: "Add your photo",
  removeBtn: "Remove",
  facePhotoReadFailed: "Failed to load",

  // ── fan ID card ─────────────────────────────────────────────────────
  fanIdHeroPrefix: "Bias",
  fanIdSelfLabel: "You",
  fanIdComplementLabel: "Complement · Discover",
  fanIdIssuedLine: (date: string) => `Issued ${date} · KSTAR Fan ID Center`,
  fanIdSampleTag: "SAMPLE",
  versionWithPhoto: "With Photo",
  versionShareOnly: "Share Only",
};
