import type { Copy } from "./copy";

export const copyEn: Copy = {
  appName: "KStar",
  appNameFull: "KStar Discovery",
  tagline: "Find your next fave",
  searchPlaceholder: "Search idols…",
  search: "Search",
  popularArtists: "Popular idols",
  featuredArtists: "Featured idols",
  similarArtistsTitle: "If you like this idol, you might also like…",
  discoverSimilar: "Discover similar idols →",
  genres: "Genres",
  noResults: "No results",
  searchResultsFor: (q: string) => `Results for “${q}”`,
  artistsSection: "Idols",
  favorite: "Favorite",
  favorited: "Favorited",
  myFavorites: "My favorites",
  noFavorites: "You haven't favorited any idols yet.",
  backHome: "Back home",
  loginCta: "Sign in to sync favorites across devices",
  viewArtist: "View idol",
  startBtn: "Start over",
  taskbarLabel: "♪ K-pop picks",

  // ── fan soul / onboarding quiz ─────────────────────────────────────
  soulCtaTitle: "Curious about your fan soul?",
  soulCtaSub: "Answer a few questions to unlock your fan personality card ✦",
  soulCtaStart: "Start the quiz →",
  soulCtaSkip: "Just browsing",
  rankTitle: "What pulls you in first?",
  rankSub: "Move what you care about most to the top (tap to move up)",
  rankHint: "#1 matters most → #4 least",
  quizProgress: (i: number, n: number) => `Question ${i} / ${n}`,
  quizBack: "← Previous",
  resultTitle: "Your fan soul",
  resultHidden: "Hidden side",
  resultSoulmate: "Souls like yours",
  resultExpand: "Want to widen your world? Try",
  resultWallClimb: "You're most likely to bias-swap to",
  resultRecap: "Your defining picks",
  shareDownload: "Download fan card",
  shareShare: "Share ✦",
  shareHint: "Screenshot it to your story so friends can test too",
  // invite link — sends newcomers to the first-encounter onboarding at "/"
  inviteBtn: "✦ Copy invite link",
  inviteCopied: "Copied — send it to a friend ✓",
  inviteText: "Find your fan soul on KStar and meet your bias ✦",
  reshareEntry: "My fan soul",
  takeQuiz: "Find my fan soul",
  soulEvolving: "Your fan soul is evolving",
  // result views (toggle + report)
  viewStory: "Story card",
  viewReport: "Full report",
  storyCta: "Find your fan soul →",
  reportLayers: "The four layers",
  reportAnswers: "Your answers",
  reportUniverse: "Your fan universe",
  reportContrast: "Contrast vs. consistency",
  reportVisual: "The visual type that gets you",
  reportResonance: "What resonates with you most",
  shareDownloadStory: "Download story card",
  shareDownloadReport: "Download full report",
  redoQuiz: "Retake the quiz",
  // fan pass
  viewPass: "Fan pass",
  passPickIdol: "Who is this fan pass for?",
  passUploadTitle: "Add your photo",
  passUploadHint: "Stays on your device — never uploaded ✦",
  passUploadBtn: "Choose photo",
  passCropTitle: "Adjust your ID photo",
  passCropHint: "Drag to move, slide to zoom",
  passCropConfirm: "Done — make my fan pass ✦",
  passRetake: "Pick another photo",
  passChangeIdol: "← Change idol",
  passNameLabel: "Your name",
  passNamePlaceholder: "Enter a nickname…",
  passMember: "MEMBER",
  passSince: (y: number) => `since ${y}`,
  passFooter: "✦ CHEERING ✦",
  passSeal: "CHEERING",
  passSolo: "✦ SOLO ✦",
  passDownload: "Download fan pass",
};
