export const copyZh = {
  appName: "KStar",
  appNameFull: "KStar 推薦",
  tagline: "喜歡這位偶像，你也會愛上這些",
  searchPlaceholder: "搜尋偶像…",
  search: "搜尋",
  popularArtists: "熱門偶像",
  featuredArtists: "精選偶像",
  similarArtistsTitle: "喜歡這位偶像，你可能也會喜歡…",
  discoverSimilar: "探索相似偶像 →",
  genres: "曲風",
  noResults: "找不到結果",
  searchResultsFor: (q: string) => `「${q}」的搜尋結果`,
  artistsSection: "偶像",
  favorite: "收藏",
  favorited: "已收藏",
  myFavorites: "我的收藏",
  noFavorites: "你還沒有收藏任何偶像。",
  backHome: "回首頁",
  loginCta: "登入以跨裝置同步收藏",
  viewArtist: "查看偶像",
  startBtn: "重新開始",
  taskbarLabel: "♪ K-pop 推薦",
  navDirectory: "偶像圖鑑",
  footerCredit: "以曲風與後設資料推薦 · 資料來源 Spotify",
  footerSubmit: "✦ 投稿偶像照片",
  bugReportLabel: "回報問題",
  bugReportSubject: "KStar 回報問題",
  bugReportBody: "請描述你遇到的問題（含畫面與重現步驟）：\n\n",

  // ── 偶像圖鑑 (directory) ──────────────────────────────────────────
  dirCountSuffix: " 位偶像",
  viewList: "列表",
  viewStar: "星圖",
  filterGender: "性別",
  filterGen: "世代",
  filterPos: "定位",
  noMatches: "沒有符合的偶像 — 放寬一下篩選吧",
  showingPrefix: "顯示 ",
  perPageLabel: "每頁",
  prevPage: "‹ 上一頁",
  nextPage: "下一頁 ›",
  addToFourCutsAria: (name: string) => `把 ${name} 換進人生四格`,
  addToFourCutsTitle: "換進人生四格",

  // ── 人生四格 / onboarding picker ──────────────────────────────────
  obTitlePick: "選出你的 TOP 4",
  fourCutsTitle: "你的人生四格",
  obTitleQuiz: "追星靈魂測驗",
  obPickPrompt: "你最喜歡的四位偶像？",
  obPickCount: (n: number, max: number) => `選出你的 Top 4 · 已選 ${n}/${max}`,
  obSkip: "先跳過",
  obDevelop: "沖洗照片 →",
  obFourCutsSub: "和你的本命合照一張",
  obAnalyzing: "分析你的品味中…",
  obRepick: "← 重選",
  noTop4: "還沒選出你的 TOP 4",
  pickTop4Btn: "選出你的 TOP 4 →",
  repickBtn: "重新挑選 ✎",
  swapTitle: "替換人生四格",
  swapIncoming: "即將換上",
  swapPrompt: "點一格換掉它 ↓",
  swapThisCut: "換掉這格",
  cancel: "取消",
  addPhoto: "補照片",
  addPhotoAria: (name: string) => `幫 ${name} 補照片`,

  // ── 追星靈魂 / 入坑問卷 ────────────────────────────────────────────
  soulCtaTitle: "想知道你的追星靈魂？",
  soulCtaSub: "回答幾題，解鎖你專屬的追星人格卡 ✦",
  soulCtaStart: "開始測驗 →",
  soulCtaSkip: "先逛逛就好",
  rankTitle: "入坑優先序",
  rankSub: "把你最在意的拖到最前面（點一下往上移）",
  rankHint: "#1 最重要 → #4 還好",
  quizProgress: (i: number, n: number) => `第 ${i} / ${n} 題`,
  quizBack: "← 上一題",
  resultTitle: "你的追星靈魂",
  resultHidden: "隱藏面",
  resultSoulmate: "和你同類的靈魂",
  resultExpand: "想拓寬世界？試試",
  resultWallClimb: "你最容易爬牆到",
  resultRecap: "你的代表偶像",
  shareDownload: "下載追星卡",
  shareShare: "分享 ✦",
  shareHint: "截圖分享到限動，讓朋友也測一張",
  // invite link — sends newcomers to the first-encounter onboarding at "/"
  inviteBtn: "✦ 複製邀請連結",
  inviteCopied: "已複製，貼給朋友 ✓",
  inviteText: "來 KStar 測你的追星靈魂，找到你的本命 ✦",
  reshareEntry: "我的追星靈魂",
  takeQuiz: "測我的追星靈魂",
  soulEvolving: "你的追星靈魂正在進化",
  processing: "處理中…",
  exportFailedReport: "圖片匯出失敗 — 直接長按／截圖這份報告分享吧 ✦",
  exportFailedStory: "圖片匯出失敗 — 直接長按／截圖這張卡分享吧 ✦",
  exportFailedPass: "圖片匯出失敗 — 直接長按／截圖分享吧 ✦",
  doneBtn: "✦ 完成",
  contrastYesLine: "反差萌 — 台上台下兩個樣最迷人",
  contrastNoLine: "始終如一 — 怎麼看都是同一個人",
  soulmateNote: "你們會一起爬牆",
  expandNote: "補上你還沒探索的那一面",
  wallClimbNote: "你的下一個本命，可能在這裡",
  wallClimbGroupSuffix: (name: string) => `「${name}」那一掛`,
  shareTextReport: (name: string, code: string) => `我是「${name}」(${code}) ✦ 來測你的 →`,
  compatSuffix: (pct: number) => `契合 ${pct}%`,
  constelLoading: "正在排列你的星圖…",
  constelNeedPicks: "先選出你的 Top 4，才能看你的專屬星圖 ✦",
  constelStart: "開始挑選 →",
  constelTitle: "✦ 你的追星星圖",
  nextStep: "下一步 →",
  moveUp: "往上移",
  moveDown: "往下移",
  defaultPickName: "他",
  defaultOutlierName: "其中一位",
  soulLabel: "追星靈魂",
  passShareText: (topLabel: string) => `${topLabel} 應援卡 ✦`,
  loadingLabel: "讀取中…",

  // ── artist page analysis sections ───────────────────────────────────
  analysisIdol: "偶像分析",
  analysisAesthetic: "美學分析",
  analysisPersonality: "個性分析",
  analysisPerformance: "表演分析",
  analysisContent: "內容分析",
  colorLabel: "色彩",
  officialStyle: "官方造型",
  personalStyle: "私服風格",
  instagramLabel: (handle: string) => `Instagram @${handle}`,
  similarTraitsPrefix: (traits: string) => `相似特質：${traits}`,

  // ── intro splash flash-warning gate ─────────────────────────────────
  introGateTitle: "⚠ 動畫含閃光",
  introGateHeading: "開場動畫包含閃爍效果",
  introGateBody: "開場動畫含有閃光，可能影響光敏感族群。要播放嗎？",
  introPlayBtn: "播放動畫",
  introCalmBtn: "平靜版本",

  // ── /submit portal ───────────────────────────────────────────────────
  submitPageTitle: "投稿偶像照片 · KSTAR",
  submitNotConfiguredTitle: "✦ 投稿功能尚未啟用 ✦",
  submitNotConfiguredBody: "此站台目前未設定投稿後端。",
  submitBadge: "✦ 幫忙補上偶像照片 ✦",
  submitTitle: "這些偶像還缺照片",
  submitSub: "點一位開始投稿 · 只收自由授權（CC／自有）",
  submitSearchPlaceholder: "🔍 找其他偶像（已有照片也能投替換）…",
  submitMissingTag: "缺照",
  submitChangeIdol: "← 換一位偶像",
  submitSelected: "✓ 已選",
  submitPhotoLabel: "照片",
  submitSourceLabel: "出處連結（必填）",
  submitLicenseLabel: "授權",
  submitCreditLabel: "署名（選填）",
  submitCreditPlaceholder: "你的名字／IG，會顯示為 credit",
  submitBtnBusy: "送出中…",
  submitBtnIdle: "送出投稿 → 等待審核",
  submitSuccessBadge: "✦ 投稿成功 ✦",
  submitSuccessMsg: (name: string) => `${name} 的照片已送出，審核通過後會上線。謝謝你！`,
  submitAgain: "← 再投一位",
  submitErrorDefault: "送出失敗",
  licenseOwn: "我本人拍攝",
  favoritesStorageNote: "收藏目前儲存在這個瀏覽器中。（設定 Supabase 後可跨裝置同步）",
  // result views (toggle + report)
  viewStory: "限動卡",
  viewReport: "完整報告",
  storyCta: "測你的追星靈魂 →",
  reportLayers: "四層拆解",
  reportAnswers: "你的答案",
  reportUniverse: "追星宇宙",
  reportContrast: "反差 vs 始終如一",
  reportVisual: "電到你的視覺型",
  reportResonance: "你最有共鳴的",
  shareDownloadStory: "下載限動卡",
  shareDownloadReport: "下載報告長圖",
  redoQuiz: "重做測驗",
  // 追星證 (Fan ID — deployed rebrand of the former 應援卡)
  viewPass: "追星證",
  passPickIdol: "這張追星證要為哪一位？",
  passUploadTitle: "放上你的大頭照",
  passUploadHint: "只留在你的裝置上，不會上傳 ✦",
  passUploadBtn: "選擇照片",
  passCropTitle: "調整你的證件照",
  passCropHint: "拖曳移動、滑桿縮放",
  passCropConfirm: "完成，生成追星證 ✦",
  passRetake: "重新選照片",
  passChangeIdol: "← 換一位",
  passNameLabel: "你的名字",
  passNamePlaceholder: "輸入暱稱…",
  passMember: "MEMBER",
  passSince: (y: number) => `since ${y}`,
  passFooter: "✦ 應援中 ✦",
  passSeal: "應援中",
  passSolo: "✦ SOLO ✦",
  passDownload: "下載追星證",

  // ── deployed brand hero + 追星證 wizard/fan-ID (from deployed copy.ts) ──
  taglineEn: "KSTAR SOULCUTS",
  wizStartCta: "開始建立追星檔案",
  wizLandingNote: "三分鐘，領取你的追星證",
  wizEscape: "先逛逛偶像圖鑑 →",
  wizStep1: "建立本命欄",
  wizStep2: "追星風格測驗",
  wizStep3: "判定結果",
  wizStep4: "領取追星證",
  wizNext: "下一步",
  wizBack: "返回",
  wizDevelop: "沖洗照片 →",
  wizIssueCta: "領取我的追星證 →",
  wizPrinting: "製卡中…",
  wizDone: "進入我的追星基地 →",
  wizPickHint: (n: number) => `已選 ${n}/4 位本命`,
  fanIdName: "追星證",
  fanIdHolder: "持卡人",
  fanIdSong: "本命曲",
  fanIdScanMe: "掃碼做你的追星證",
  fanIdClaim: "領取你的追星證",
  myFanId: "我的追星證",
  fanIdBrandHeading: "KSTAR 發證中心",
  fanIdBrandSub: "先建立你的追星檔案",
  storyFrequency: "你的追星頻率",

  // ── /start wizard ──────────────────────────────────────────────────
  wizCenterSuffix: "發證中心",
  startPageTitleSuffix: "領取你的追星證",
  wizDeveloping: "顯影中…",
  wizDevelopFailed: "顯影失敗，請返回再試一次。",
  wizResultLoadFailed: "無法載入判定結果，請返回再試一次。",
  wizNeedFourPicks: "追星證需要四位本命，請返回重新選擇。",
  wizNeedArchetype: "尚未完成追星型別判定，請返回測驗。",
  wizCardLoadFailed: "無法載入製卡資料，請返回再試一次。",
  wizPreparingCard: "準備製卡資料…",
  wizUnderConstruction: "施工中",
  wizStepsAria: "步驟",
  wizQuizComplete: "測驗已完成 ✦",
  wizViewResult: "查看判定結果 →",
  wizRedoQuiz: "↻ 重做測驗",
  wizPickThumbsAria: "本命欄縮圖",
  wizQuizProgressAria: "問卷進度",
  wizDefaultPickName: "他",

  // ── /start wizard: step picker ────────────────────────────────────
  wizPickSlotLabel: "本命欄",
  wizSwapHint: (name: string) => `${name} — 點兩格交換位置`,
  wizRemoveAria: (name: string) => `移除 ${name}`,
  wizEmptySlotAria: (n: number) => `空白本命欄 ${n}`,
  wizPickToggleAria: (picked: boolean, name: string) => `${picked ? "移除" : "選擇"} ${name}`,
  pagePrevAria: "上一頁",
  pageNextAria: "下一頁",
  filterAllGen: "全部世代",

  // ── /start wizard: reveal ──────────────────────────────────────────
  shareTabsAria: "選擇分享內容",
  shareTabReport: "完整長圖",
  shareStudioAria: "分享追星結果",

  // ── /start wizard: issue (fan ID ceremony) ─────────────────────────
  wizIncompleteAlert: "追星證資料不完整，請返回重新選擇四位本命。",
  wizFocusLabel: "選擇本命焦點",
  wizFanNameLabel: "持卡人（選填）",
  wizCardVersionLabel: "卡片版本",
  wizVersionA: "Version A · 本人版",
  wizVersionB: "Version B · 純分享版",
  wizBiasSongComingSoon: "本命曲 ♪ · 咕卡 deco — 即將推出",
  wizExporting: "匯出中…",
  wizExportStory: "匯出限動 9:16",
  wizExportCard: "匯出卡片",
  wizExportFailedGeneric: "圖片匯出失敗，請稍後重試或直接截圖。",
  wizReplay: "↻ 重播製卡",
  wizSaveFailed: "無法儲存追星證，請確認瀏覽器儲存空間後再試一次。",
  customizeFanIdAria: "自訂追星證",

  // ── face photo picker ───────────────────────────────────────────────
  closeAria: "關閉",
  photoZoomAria: "照片縮放",
  cropBusy: "裁切中…",
  cropConfirmBtn: "使用這張照片",
  photoProcessFailed: "照片處理失敗，請換一張再試。",
  facePhotoChange: "更換本人照片",
  facePhotoAdd: "加入本人照片",
  removeBtn: "移除",
  facePhotoReadFailed: "讀取失敗",

  // ── fan ID card ─────────────────────────────────────────────────────
  fanIdHeroPrefix: "本命",
  fanIdSelfLabel: "本人",
  fanIdComplementLabel: "互補型 · 發現",
  fanIdIssuedLine: (date: string) => `發證 ${date} · KSTAR 發證中心`,
  fanIdSampleTag: "SAMPLE · 示意",
  versionWithPhoto: "本人版",
  versionShareOnly: "純分享版",
};
