export const copy = {
  appName: "KStar",
  appNameFull: "KStar 推薦",
  tagline: "喜歡這位偶像，你也會愛上這些",
  taglineEn: "FIND YOUR NEXT FAVE",
  searchPlaceholder: "搜尋偶像…",
  search: "搜尋",
  popularArtists: "熱門偶像",
  featuredArtists: "精選偶像",
  similarArtistsTitle: "喜歡這位偶像，你可能也會喜歡…",
  discoverSimilar: "探索相似偶像 →",
  genres: "曲風",
  noResults: "找不到結果",
  searchResultsFor: (q: string) => `「${q}」的搜尋結果`,
  artistsSection: "偶像",
  favorite: "收藏",
  favorited: "已收藏",
  myFavorites: "我的收藏",
  noFavorites: "你還沒有收藏任何偶像。",
  backHome: "回首頁",
  loginCta: "登入以跨裝置同步收藏",
  viewArtist: "查看偶像",
  startBtn: "✦ 開始",
  taskbarLabel: "♪ K-pop 推薦",
} as const;
