// GENERATED by scripts/gen-type-rarity.ts — do not edit by hand.
export const TYPE_RARITY: Record<string, number> = {
  "apsr": 38.7,
  "Apsr": 9.6,
  "apsR": 9.0,
  "aPsr": 6.9,
  "apSr": 6.8,
  "aPsR": 3.9,
  "ApsR": 3.6,
  "ApSr": 3.0,
  "APsr": 2.9,
  "apSR": 2.7,
  "ApSR": 2.6,
  "aPSr": 2.6,
  "APsR": 2.3,
  "APSR": 2.3,
  "aPSR": 1.7,
  "APSr": 1.2,
};
