// Monte-Carlo the 16-type distribution: N random 4-pick cohorts → getArchetype.
// Re-run after any catalog change:
//   npx tsx scripts/gen-type-rarity.ts

import * as fs from "node:fs";
import catalogJson from "../src/data/catalog.json";
import { ARCHETYPES, getArchetype } from "../src/lib/archetypes";
import { rankToWeights } from "../src/lib/questionnaire";
import { similarArtists } from "../src/lib/similarity";
import {
  SCORE_LAYERS,
  type Artist,
  type LayerScores,
  type PickSummary,
} from "../src/lib/types";

const N = 20_000;
const artists = (catalogJson as { artists: Artist[] }).artists.filter((artist) => artist.profile);

// Seeded PRNG and unique four-pick sampling mirror calibrate-archetypes.ts so
// catalog changes, rather than random runtime noise, drive generated diffs.
let seed = 1_234_567;
const rand = () => ((seed = (seed * 1_103_515_245 + 12_345) & 0x7fffffff) / 0x7fffffff);

function sampleRandomFour(): Artist[] {
  const picks: Artist[] = [];
  const used = new Set<number>();
  while (picks.length < 4) {
    const index = Math.floor(rand() * artists.length);
    if (!used.has(index)) {
      used.add(index);
      picks.push(artists[index]);
    }
  }
  return picks;
}

// Mirrors calibrate-archetypes.ts pickStrengths/getPickSummaries: each pick's
// layer strength is its mean pairwise similarity against the other three.
function cohesionSummaries(group: Artist[]): PickSummary[] {
  return group.map((pick) => {
    const others = group.filter((other) => other.id !== pick.id);
    const sims = similarArtists(pick, others, undefined, others.length);
    const n = sims.length || 1;
    const scores: LayerScores = { aesthetic: 0, personality: 0, performance: 0, content: 0 };
    for (const sim of sims) {
      for (const layer of SCORE_LAYERS) scores[layer] += sim.layerScores[layer];
    }
    for (const layer of SCORE_LAYERS) scores[layer] /= n;

    return {
      id: pick.id,
      layerScores: scores,
      tokens: {
        lifestyle_topics: [],
        value_topics: [],
        style_tags: [],
        color_palette: [],
      },
    };
  });
}

// An empty ranking leaves rankToWeights' four defaults equal at 0.25 each,
// avoiding a synthetic preference for any A·P·S·R axis in the population.
const weights = rankToWeights([]);
const counts: Record<string, number> = Object.fromEntries(
  Object.keys(ARCHETYPES).map((code) => [code, 0]),
);

for (let i = 0; i < N; i++) {
  const result = getArchetype(cohesionSummaries(sampleRandomFour()), weights);
  counts[result.code] = (counts[result.code] ?? 0) + 1;
}

const lines = Object.entries(counts)
  .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
  .map(([code, count]) => `  ${JSON.stringify(code)}: ${((count / N) * 100).toFixed(1)},`);

fs.writeFileSync(
  "src/lib/typeRarity.ts",
  "// GENERATED by scripts/gen-type-rarity.ts — do not edit by hand.\n" +
    `export const TYPE_RARITY: Record<string, number> = {\n${lines.join("\n")}\n};\n`,
);

console.log("wrote src/lib/typeRarity.ts");
